### ISSUE TITLE
Permission to host code

### ISSUE THREAD

**Issue by aclark4life** [aclark4life/worldcookery#1]
So this code is here now, hopefully OK w/@philikon? And/or Springer?

**Comment by philikon** [comment]
This is ok with me so long as it's attributed. The description of the repo on GitHub is good. Perhaps add a README or COPYRIGHT file so that clones of the repo contain that info?

**Comment by aclark4life** [comment]
@philikon OK added readme, thanks. Let me know if you'd like a copyright statement and if so what it should say.

**Comment by philikon** [comment]
Cool thanks! I honestly don't know about the copyright of the code. I guess it's part of the book, so whatever the book is under? IANAL.

**Comment by aclark4life** [comment]
The book contains a statement like "subject to copyright" whatever that means; IANAL either. If I had to guess, I'd say Springer is the copyright holder… maybe I'll add a statement to that effect.

**Comment by philikon** [comment]
Sounds good to me. Thanks!
